import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { MiniKitProvider } from '@worldcoin/minikit-js/minikit-provider'
import { VerificationProvider } from '@/contexts/verification-context'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { clientLogger } from '@/lib/client-logger'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <MiniKitProvider>
        <VerificationProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Toaster />
          </body>
        </VerificationProvider>
      </MiniKitProvider>
    </html>
  )
}
